### ISSUE TITLE
ты еблан

### ISSUE THREAD

**Issue by ZenovJB** [TheKisDevs/LavaHack-Public#1]
иди нахуй очкарик

**Comment by kisman2000** [comment]
что тебе не нравится я вообще не понимаю, слил украинский кодер который конченый долбоёб если честно, я лишь перезалил это на свой гитхаб, лику месяц-два, пусть будет фри версией, мб даже контрибьютить будут

**Comment by ZenovJB** [comment]
lambo truck went drizzy on dat beat vruh
