### ISSUE TITLE
I cant open the gui even when i hit Rshift

### ISSUE THREAD

**Issue by Gabe730** [TheKisDevs/LavaHack-Public#18]

**Comment by kisman2000** [comment]
hello can you send .minecraft/logs/latest.log

**Comment by Gabe730** [comment]
[latest.log](https://github.com/TheKisDevs/LavaHack-Public/files/10525300/latest.log)

**Comment by Gabe730** [comment]
thank you for trying

**Comment by kisman2000** [comment]
hello you should download lh from actions page
