### ISSUE TITLE
Do you have anything that isn't stolen?

### ISSUE THREAD

**Issue by Nutelaspaceman** [TheKisDevs/LavaHack-Public#5]
Istg you Jew shit off GitHub and post it 💀 I uploaded that like yesterday that wasnt when the leak happened

**Comment by master7720** [comment]
woah woah dont talk to kissmen like that he has a major brain tumor it makes him paste everything its not it fault

**Comment by Nutelaspaceman** [comment]
> woah woah dont talk to kissmen like that he has a major brain tumor it makes him paste everything its not it fault

fr 🙏
